name: Wakatime Charts

on:
  workflow_dispatch:
  schedule:
    - cron: "*/1000 * * * *"

jobs:
  update-charts:
    name: Update wakatime stats charts
    runs-on: ubuntu-latest
    steps:
      - uses: dvjn/wakatime-charts@master
        with:
          IMAGES_FOLDER: "images"
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
